version: '3.2'

services:
   backend-kafka:
      build: .
      container_name: backend-kafka
      volumes:
        - ".:/app"
      env_file:
      - ./.env

networks:
   default:
      external: true
      name: appvideos